language: ruby
rvm:
 - '2.3.1'
# uncomment this line if your project needs to run something other than `rake`:
#script: bundle exec rspec spec
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
services:
  - postgresql
addons:
  postgresql: "9.6"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
